server: 
  port: 9008
spring: 
  application:  
    name: forum-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_user?characterEncoding=UTF8
    username: root
    password: cc123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 47.98.135.4
    password: root

  rabbitmq:
    host: 47.98.135.4
    password: admin
    username: admin


eureka:
  client:
    service-url:
      defaultZone: http://47.98.135.4:6868/eureka/

  instance:
    prefer-ip-address: true