server: 
  port: 9003
spring: 
  application:  
    name: forum-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_qa?characterEncoding=UTF8
    username: root
    password: cc123456
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    prefer-ip-address: true