server:
  port: 12000



spring:
  application:
    name: forum-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chainchain/forum_config_file.git
          password: cq19990117
          username: 1759683080@qq.com

