server:
  port: 12000



spring:
  application:
    name: forum-config
  cloud:
    config:
      server:
#        git:
  
#  rabbitmq:


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

