server:
  port: 12000



spring:
  application:
    name: forum-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chainchain/forum_config_file.git
          password: cq19990117
          username: 1759683080@qq.com
  rabbitmq:
    host: 47.98.135.4
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

