server: 
  port: 9001
spring: 
  application:  
    name: forum-base #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3307/tensquare_base?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 47.98.135.4
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    prefer-ip-address: true

