server: 
  port: 9004
spring: 
  application:  
    name: forum-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_article?characterEncoding=UTF8
    username: root
    password: cc123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 47.98.135.4
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    preferIpAddress: true


