server:
  port: 9010

spring:
  application:
    name: forum-friend

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_friend?characterEncoding=UTF8
    username: root
    password: cc123456

  jpa:
    database: mysql
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

  instance:
    prefer-ip-address: true


#开启熔断器
feign:
  hystrix:
    enabled: true