server:
  port: 9012
spring:
  application:
    name: forum-web



eureka:
  client:
    service-url:
      defaultZone: http://47.98.135.4:6868/eureka/

  instance:
    prefer-ip-address: true



#网关配置部分
zuul:
  routes:
    forum-base:
      path: /base/**
      servicdId: forum-base
    forum-user:
      path: /user/**
      servicdId: forum-user
