server: 
  port: 9005
spring: 
  application:  
    name: forum-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_gathering?characterEncoding=UTF8
    username: root
    password: cc123456
  jpa: 
    database: MySQL
    show-sql: true
