server: 
  port: 9002
spring: 
  application:  
    name: forum-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.135.4:3306/forum_recruit?characterEncoding=UTF8
    username: root
    password: cc123456
  jpa: 
    database: MySQL
    show-sql: true
